### PR TITLE
Landing page

### PR DESCRIPTION
**Pull request by amyyalex**

### CODE REVIEW

**Review by HassanBahati — CHANGES_REQUESTED** [review]
@amyyalex please adjust these few warning so that we can merge
Screenshot from 2022-10-03 14-02-02

**Comment by amyyalex** [comment]
> @amyyalex please adjust these few warning so that we can merge Screenshot from 2022-10-03 14-02-02

Alright

**Comment by amyyalex** [comment]
@HassanBahati I have fixed the warning issues.

**Comment by HassanBahati** [comment]
thank you @amyyalex

**Pull request merged**
