### PR TITLE
Landing page

### PR DESCRIPTION
**Pull request by amyyalex**
@HassanBahati Kindly review and merge to the master
Thanks

### CODE REVIEW

**Comment by HassanBahati** [comment]
Thanks @amyyalex i am going to review. Pleases briefly decribe the changes in terms of what is new to the home page through this pr

**Review by HassanBahati — APPROVED** [review]
LGTM

**Comment by amyyalex** [comment]
> Thanks @amyyalex i am going to review. Pleases briefly decribe the changes in terms of what is new to the home page through this pr

Sure, I added a banner section, modified the folder structure, routed the pages to one another and linked the buttons.

**Comment by amyyalex** [comment]
> LGTM

Thanks

**Pull request merged**
